
" Configuration files
" ----------------------------------------------------------------

" Plugins
source $HOME/.vim/config/plugins.vim

" Settings
source $HOME/.vim/config/global-settings.vim

" Plugin-specific settings
source $HOME/.vim/config/plugin-settings.vim

" Custom commands
source $HOME/.vim/config/commands.vim

" Custom mappings
source $HOME/.vim/config/custom-mappings.vim

" Macros
source $HOME/.vim/config/macros.vim

