# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Theme
ZSH_THEME="agnoster"


# Configuration
# -----------------------------------------------------------------------------
source $HOME/.zsh/config/options.zsh
source $HOME/.zsh/config/aliases.zsh

source $ZSH/oh-my-zsh.sh
# Composer
# -----------------------------------------------------------------------------
export PATH="/Users/serega/.composer/vendor/bin:$PATH"

# Binary
# -----------------------------------------------------------------------------
export PATH="/usr/local/sbin:/opt/local/bin:$PATH"

# PHP5.6
# -----------------------------------------------------------------------------
export PATH="/usr/local/opt/php56/bin:$PATH"

# VirtualBox
# -----------------------------------------------------------------------------
export PATH="/Applications/VirtualBox.app/Contents/MacOS:$PATH"

# Pear
# -----------------------------------------------------------------------------
export PATH="/Users/serega/pear/share/pear:$PATH"
export PATH="/Users/serega/pear/bin:$PATH"


# Nodejs
# -----------------------------------------------------------------------------
export NODE_PATH="/usr/local/lib/node_modules"
export PATH="$HOME/.node/bin:$PATH"
