# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Theme
ZSH_THEME="agnoster"


# Configuration
# -----------------------------------------------------------------------------
source $HOME/.zsh/config/options.zsh
source $HOME/.zsh/config/aliases.zsh
source $HOME/.zsh/config/paths.zsh

source $ZSH/oh-my-zsh.sh
